import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class SubstitutionCipher:
    def decode(self, a, b, y):
    	if not (set(a)<set(b)):
    		return ""
    	h={}
	for i in range (len(a)):
		h[a[i]]=b[i]
	d=[None]*len(y)
	for i in range(len(y)):
		d[i]=h[y[i]]
	return ''.join(d)
    	
# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, hasAnswer, p3):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("\"") + str(p0) + str("\"") + str(",") + str("\"") + str(p1) + str("\"") + str(",") + str("\"") + str(p2) + str("\""))
	print(str("]"))
	obj = SubstitutionCipher()
	startTime = time.clock()
	answer = obj.decode(p0, p1, p2)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str("\"") + str(p3) + str("\""))
	
	print(str("Your answer:"))
	print(str("\t") + str("\"") + str(answer) + str("\""))
	if (hasAnswer):
		res = answer == p3
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = "CAT"
p1 = "DOG"
p2 = "GOD"
p3 = "TAC"
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, p2, True, p3) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = "BANANA"
p1 = "METETE"
p2 = "TEMP"
p3 = ""
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, p2, True, p3) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = "THEQUICKBROWNFOXJUMPSOVERTHELAZYHOG"
p1 = "UIFRVJDLCSPXOGPYKVNQTPWFSUIFMBAZIPH"
p2 = "DIDYOUNOTICESKIPPEDLETTER"
p3 = "CHCXNTMNSHBDRJHOODCKDSSDQ"
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, p2, True, p3) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
